version: "3"

networks:
  laravel5:

services:
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    networks:
      - laravel5
    container_name: "php5"
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - laravel5
    depends_on:
      - php
      - mysql
    container_name: "nginx5"


  mysql:
    image: mysql:5.7.22
    container_name: "mysql5"
    restart: unless-stopped
    tty: true
    networks:
      - laravel5
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./env/mysql.env
